### ISSUE TITLE
Question re: using with Android

### ISSUE THREAD

**Issue by narner** [orsjb/beads#15]
More a question than anything, but is it possible to use the Beads library on an Android device? I've been trying to run the Beads example projects via Processing for Android, but none seem to run - I'm trying to determine whether this is an issue with running on an Emulator, or something else...wanted to figure that out before I purchase an actual Android device. Thanks!

**Comment by orsjb** [comment]
Beads can be made to run on Android but you need to write a new AudioIO class that will enable the Beads system to stream realtime audio in and out. I can do this but it’s low on my priority list. It should be quite easy once you have an Android development environment set up.

Ollie

**Comment by narner** [comment]
Ah, good to know - thank you! Unfortunately my Java knowledge is quite limited to Processing (have not done any native Android development at all yet).

**Comment by cwong4311** [comment]
Closing this issue as the original question has been be answered.
