### ISSUE TITLE
newbie: ac.start() --> line unsupported error

### ISSUE THREAD

**Issue by intheminorKey** [orsjb/beads#17]
not making a sound unfortunately. any fix ideas anyone?
AudioContext : no AudioIO specified, using default => net.beadsproject.beads.core.io.JavaSoundAudioIO.
JavaSoundAudioIO: Chosen mixer is Port Speakers (Conexant SmartAudio H.
Exception in thread "Thread-0" java.lang.IllegalArgumentException: Line unsupported: interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, big-endian
	at java.desktop/com.sun.media.sound.PortMixer.getLine(Unknown Source)
	at net.beadsproject.beads.core.io.JavaSoundAudioIO.create(Unknown Source)
	at net.beadsproject.beads.core.io.JavaSoundAudioIO$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by orsjb** [comment]
What system?

**Comment by intheminorKey** [comment]
wow. sorry. they tell me i'm too cryptic at work also.

windows 10.

i printed the mixer list and set the JSAudio mixer to another one and it worked.

i was being a little lazy and unconfident earlier i think; now i'm quite pleased with myself!

i've had the java synthesis book on my ereader for a couple of years and finally started today.

i had to download everything from scratch and it all got too much for me.

been a good few years since i tried programming of any kind.

it's reassuring to know you care - i will try a bit harder myself next time before sending out any more SOSs.

thanks,  charles.


________________________________

**Comment by orsjb** [comment]
No worries at all ;-)
If you can, let us know which mixer worked and which one didn’t. Maybe post the print out of your mixer list.

Ollie

**Comment by cwong4311** [comment]
Closing this issue as it has been resolved and there have been no recent replies.
