### ISSUE TITLE
Status of this library ?

### ISSUE THREAD

**Issue by dhowe** [orsjb/beads#20]
I notice most of the code hasn't been updated in years -- is it still being maintained?

**Comment by orsjb** [comment]
There’s some more activity on the migrate-to-gradle branch. This project is still being actively maintained as a key component of the HappyBrackets project, albeit with no guarantees about reaching milestones.

**Comment by dhowe** [comment]
as a user, should I be using the migrate-to-gradle branch then ?

**Comment by orsjb** [comment]
Yes, this is the latest we’re working from, and it is still in active development. What we’re not really focused on is getting it all nice and smooth for others. We don’t get many requests like yours but when we do it is good motivation to get things into shape.

So either work from the latest on that branch, but prepare for a bit of fiddling, or take the more out of date end user approach and use any of the options on this site http://beadsproject.net/. 

I truly hope we can get everything up to date. As the branch name (migrate to gradle) suggests, the plan was to deliver this as a gradle / maven repo that you can incorporate directly into your projects. Also to release a new version for Processing that pushes through our changes and improvements to the library, but we just have not had that as a priority for now.

Ollie

**Comment by dhowe** [comment]
Good to know. If I end up using Beads for my project, I might be able to help out with the Processing lib, as I've written and maintained such libraries (e.g., RiTa)

**Comment by cwong4311** [comment]
Closing this issue as it has been resolved.
