### ISSUE TITLE
Granulating a stream from Audio Input

### ISSUE THREAD

**Issue by dhowe** [orsjb/beads#22]
I'm working with the example from the Processing tutorial called '7.3. Granulating from Audio Input (Granulating_Input_01)'. I'm wondering if its possible to granulate the entire audio stream (from the mic) rather than just a small recorded bit?

**Comment by orsjb** [comment]
There are no tools that directly enable this. However, you can create a sample buffer using “new Sample()” with a specified length and format, and record into it using a RecordToSample object, and then granulate the playback of that sample, simultaneously. You just need to take care of where the record head and play head are, what latency you want, how it loops etc. It’s a relatively simple and fun thing to build once you understand the basics.
