### ISSUE TITLE
Output Buffer Looping Issue when using an Audio Input

### ISSUE THREAD

**Issue by MeFisto94** [orsjb/beads#23]
Hey, I'm new to beads, so maybe I am just doing things wrong, but googleing doesn't really help in that regard, so maybe you can help me pinpoint the problem.

This issue only appears when I use the Audio Input (Commenting out gains[0].addInput(inputContext.getAudioInput());` is enough to "fix" the problem):

I currently have multiple gains which are feeded a microphone (said inputContext) and a sine wave for testing on another gain. Whenever the Microphone is part of the Output Chain, I can clearly hear the audio buffer looping for both the microphone and the sine wave (the bug is also there without the sine wave, so the microphone seems to be enough):

```java
        input = new JavaSoundAudioIO();
        float latency = 500f;
        int bufSize = Math.round(48000f / (1000f / latency));
        outputContext = new AudioContext(bufSize);
        inputContext = new AudioContext(input, bufSize, new IOAudioFormat(48000f, 16, 1, 1, true, false));

        gains[0] = new Gain(outputContext, 1, 1f);
        gains[1] = new Gain(outputContext, 1, 1f);
        outputContext.out.addInput(gains[0]);
        outputContext.out.addInput(gains[1]);

        inputContext.start();
        outputContext.start();
        gains[0].addInput(inputContext.getAudioInput());
```
So I can hear the sound perfectly fine for 500ms, then it drops out for some time and then it starts again.
Also I guess a buffer size of 50ms would be appropriate for voice? (If I go like 5ms, I have a flanger effect on it).

Edit: After some debugging I found that this issue is always present when two Audio Contexts exist. I tried it with a different Audio Context to output the same sound to two devices, exactly the same bug. I guess this is expected? Or should one be able to use multiple Audio Contexts?

**Comment by orsjb** [comment]
Hi there,

you should only ever use one AudioContext.

AudioContext ac = new AudioContext();
UGen input = ac.getAudioInput(.. etc.);
ac.out.addInput(input);	//<—direct throughput
etc...

Try that. If you had a problem doing it that way then let us know.

Ollie

**Comment by MeFisto94** [comment]
So there is no way for beads to use multiple input/output devices? Because in that case I used the mixer() method to grab a specific device, where the output device and the input device were two different mixers, so I'd need multiple contexts, but I guess the whole beads structure isn't setup for this (e.g. when I have two output contexts / an intermediary node handling this, how is the input ticked, when output A is polled? with a separate fixed timer, etc)

**Comment by orsjb** [comment]
Yes it’s not designed that way. You might be able to make it work though.
If possible it would be preferable to create an aggregate audio device and access that. You can do that in OSX. Not sure about other platforms.

Or use Jack as an interface.

**Comment by cwong4311** [comment]
Closing this issue as it has been resolved.
