### ISSUE TITLE
Spatial Sound Tutorial

### ISSUE THREAD

**Issue by gasparramoa** [orsjb/beads#27]
Hello!
First of all, thank you all for your work.

I'm interesting in using your _[Spatial Method](http://www.beadsproject.net/doc/net/beadsproject/beads/ugens/Spatial.html)_.
I have been working with JOAL for 3D audio but it's outdated while your project is still recent. 

This is the code that I already tried: (Based on tutorial Lesson04)

		AudioContext ac;

		JavaSoundAudioIO jsaIO = new JavaSoundAudioIO();
		jsaIO.selectMixer(3);
		
		ac = new AudioContext(jsaIO);

		String audioFile = "audio/1234.aif";
		SamplePlayer player = new SamplePlayer(ac, SampleManager.sample(audioFile));

		Gain g = new Gain(ac, 1, 0.2f);
		g.addInput(player);
		
		Spatial spatial = new Spatial(ac, 3, 1.0f);
				
		/*
		float[] pos = {0.0f, 0.0f, 0.0f};
		float[] pos2 = {1.0f, 1.0f, 1.0f};
		float[][] sPos = {pos, pos2};
		spatial.setLocation(g, 0, pos);
		spatial.setSpeakerPositions(sPos);
		*/

		spatial.addInput(g);
		ac.out.addInput(spatial);
		ac.start();

All of the tutorials work perfectly in my eclipse project.
But I cannot hear any sound...
I already tried to change the position of the "source" as well change the position of the "Speaker" but nothing changes.

[Edit :] I explored your [Tutorial Manual](https://evanxmerz.com/blog/wp-content/uploads/2020/09/Sonifying_Processing_The_Beads_Tutorial.pdf) but there is not information about Spatial sound.
All of the other methods work, _Gain_, _Reverb_, _Panner_, _Compressor_, etc...

Thanks in advance!
Gaspar

**Comment by orsjb** [comment]
Hi Gaspar,

I've not had time to test your code or develop an example, but I do know you need an "addInput()" line as well as the "setLocation()" line. A UGen needs to be connected first. Positioning only applies to UGens that are added. Yep, I guess this should throw an exception! 

Although it is actually more intensive, I always use the method "addInput(UGen source, UGen[][] controllers)". The second argument is an array of audio-rate controllers that controls the x,y,z positions. It's a 2D array, because, somewhat over ambitiously, I allowed that you can add multi-channel UGens in the space!

**Comment by gasparramoa** [comment]
Hello Ollie!

With the method "**addInput(UGen source, UGen[][] controllers)**" I was able to use the Spatial UGen. 
This is a script for everyone that might struggling with this method.

```
import net.beadsproject.beads.core.AudioContext;
import net.beadsproject.beads.core.UGen;
import net.beadsproject.beads.core.io.JavaSoundAudioIO;
import net.beadsproject.beads.data.SampleManager;
import net.beadsproject.beads.ugens.Gain;
import net.beadsproject.beads.ugens.Glide;
import net.beadsproject.beads.ugens.SamplePlayer;
import net.beadsproject.beads.ugens.Spatial;

public class SpatialSoundTutorial {

	Glide xGlide; //Back-Front
	Glide yGlide; //Left-Right
	Glide zGlide; //Bottom-Top
	Glide gainGlide;
	Glide freqGlide;
	
	Spatial spatial;
	Gain g;	
	SamplePlayer player;
	String audioFile = "audio/1234.aif";
	AudioContext ac;


	public SpatialSoundTutorial() {
		
		/* initialize audio context */
		JavaSoundAudioIO jsaIO = new JavaSoundAudioIO();
		jsaIO.selectMixer(3);		
		ac = new AudioContext(jsaIO);
		
		
		/* glides: */
		gainGlide = new Glide(ac, 0.5f, 50f);		
		freqGlide = new Glide(ac, 100, 100);	
		xGlide = new Glide(ac, 0f, 5000f);
		yGlide = new Glide(ac, 0.5f, 5000f); /* 0.5 - (center) Left-Right */
		zGlide = new Glide(ac, 0f, 5000f);
		
		/* UGen Controllers for Spatial */
		UGen[][] controllers = { {xGlide, yGlide, zGlide} };
		
		/* Player */
		player = new SamplePlayer(ac, SampleManager.sample(audioFile));
				
		/* gain initialization */
		g = new Gain(ac, 1, gainGlide);
		g.addInput(player);
		
				
		/* Spatial - 3D */
		spatial = new Spatial(ac, 3, 1f);
		spatial.addInput(g, controllers);

		/* Try to change the position (You can also change in the Glides definition) */
		//yGlide.setValue(1.5f);
		//xGlide.setValue(0.8f);
		//zGlide.setValue(0.8f);
		
		/* add to Audio Context */
		ac.out.addInput(spatial);
		ac.start();		
	}
	
	public static void main(String[] args) {

		new SpatialSoundTutorial();
		
	}
}
```
There are still some concepts that I truly did not understood. 
 1 - The center position of the y-axis is **0.5** and not **0**, even if you change your sphere diameter.
 2 - The sphere diameter center location is unknow and it looks more like a radius due to the following calculations:

```
          Sphere diameter = 1 : 
           x-axis(audible) ]-0.87,0.87[
           y-axis(audible) ]-1, 2[
           x-axis(audible) ]-0.87,0.87[
```

If the sphere diameter is 1 we should not be able to hear sound from the position (0,0,0.5) for example.

**Comment by orsjb** [comment]
Hi Gaspar,

> 1 - The center position of the y-axis is 0.5 and not 0, even if you change your sphere diameter.


Isn’t that because you set that in your code?

> 2 - The sphere diameter center location is unknow and it looks more like a radius due to the following calculations:

That looks very likely a typo (or bug, if you like) on my behalf. Indeed, based on the following sentence I clearly intended this to be a radius: "speakers will not play a sound that is further than 1 diameter away from them.”

Damn, it will be hard to rename everywhere from diameter to radius. I could deprecate the functions but it’s not so easy with the constructors! So I’d prefer to simply fix the amplitude calculation so that diameter actually means diameter. This might break old code. Any preference for you?

Ollie

**Comment by gasparramoa** [comment]
Hello Ollie,

> Isn’t that because you set that in your code?

If I set it to 0.0 you will notice that the sound is coming from the left speaker. Just try my code and you will see the difference.

> Damn, it will be hard to rename everywhere from diameter to radius. I could deprecate the functions but it’s not so easy with the constructors! So I’d prefer to simply fix the amplitude calculation so that diameter actually means diameter. This might break old code. Any preference for you?

I think you can keep diameter and just improve the method description and the user will understand that is radius what you mean there and not diameter, but either ways are okay for me as long the description matches.

The most important think is to get to know the center position of the sphere. At this moment I think it is at (0.0, 0.5, 0.0). 

Thanks once again for all the help!
