### ISSUE TITLE
Sample.resizeWithZeros() doesn't resize theSampleData

### ISSUE THREAD

**Issue by ceefour** [orsjb/beads#8]
I might be mistaken, but:

```
public void resizeWithZeros(long frames) {
    nFrames = frames;
}
```

seems incorrect. It should allocate a `new float[]` for `theSampleData`.

**Comment by cwong4311** [comment]
Yes, you are correct. The current implementation leads to undesired behaviour as it only changes the length pointer.

This function has been updated to properly allocate a new float array (and copy across existing data items) while zeroing out any other items, and will be available in the next release (v3.2)

Cheers
